### ISSUE TITLE
Shift menu won't appear properly

### ISSUE THREAD

**Issue by slmcnbcr** [MiguelGuthridge/Novation-LaunchKey-Mk2-Script#15] opened 2020-07-08 13:24 UTC
[output.txt](https://github.com/MiguelGuthridge/Novation-LaunchKey-Mk2-Script/files/4891362/output.txt)
I have Launchkey 61 MK2 which has the same functionality with 49 but even though I did everything in the wiki accordingly. Shift menu won't appear properly.

**Comment by MaddyGuthridge** [comment] 2020-07-08 13:28
Can't reproduce.
Requires a copy of the script output with advanced debugging enabled, which is currently impossible due to #14.
Will update when this becomes possible.

**Comment by MaddyGuthridge** [comment] 2020-07-08 14:34
Version 1.2.2 has been released and issue #14 is closed. @slmcnbcr can you get a copy of the script output now, with your debug mode set to `[internalconstants.DEBUG_LIGHTING_RESET, internalconstants.DEBUG_LIGHTING_MESSAGE]`?

**Comment by slmcnbcr** [comment] 2020-07-08 14:41
> Version 1.2.2 has been released and issue #14 is closed. @slmcnbcr can you get a copy of the script output now, with your debug mode set to `[internalconstants.DEBUG_LIGHTING_RESET, internalconstants.DEBUG_LIGHTING_MESSAGE]`?

FL Studio Midi scripting version: 4
"C:\Users\User\Documents\Image-Line\Data\FL Studio\Settings\Hardware\Novation-LaunchKey-Mk2-Script-1.2.2\device_LaunchKey49 port 2.py" found

init ok
Successfully imported:  fpc
Successfully imported:  bbcso
————————————————————————————————————————————————————
Novation LaunchKey Mk2 Controller Script - Version: 1.2.2
 - Miguel Guthridge

Running in FL Studio Version: Producer Edition v20.7.1 [build 1773]
FL Studio Scripting version: 4. Minimum recommended version: 4
Advanced debugging is enabled: ['Lighting reset', 'Lighting message']

Sent lighting reset signal
Sent lighting command [0, 1] (InControl Disabled)
Sent lighting command [0, 1] (InControl Disabled)
Sent lighting command [1, 1] (InControl Disabled)
Sent lighting command [0, 0] (InControl Disabled)
Sent lighting command [0, 1] (InControl Disabled)
Sent lighting command [1, 1] (InControl Disabled)
Sent lighting command [0, 0] (InControl Disabled)
Sent lighting command [2, 1] (InControl Disabled)
Sent lighting command [1, 0] (InControl Disabled)
Sent lighting command [0, 1] (InControl Disabled)
Sent lighting command [1, 1] (InControl Disabled)
Sent lighting command [0, 0] (InControl Disabled)
Sent lighting command [2, 1] (InControl Disabled)
Sent lighting command [1, 0] (InControl Disabled)
Sent lighting command [3, 1] (InControl Disabled)
Sent lighting command [2, 0] (InControl Disabled)
Sent lighting command [0, 1] (InControl Disabled)
Sent lighting command [1, 1] (InControl Disabled)
Sent lighting command [0, 0] (InControl Disabled)
Sent lighting command [2, 1] (InControl Disabled)
Sent lighting command [1, 0] (InControl Disabled)
Sent lighting command [3, 1] (InControl Disabled)
Sent lighting command [2, 0] (InControl Disabled)
Sent lighting command [4, 1] (InControl Disabled)
Sent lighting command [3, 0] (InControl Disabled)
Sent lighting command [0, 1] (InControl Disabled)
Sent lighting command [1, 1] (InControl Disabled)
Sent lighting command [0, 0] (InControl Disabled)
Sent lighting command [2, 1] (InControl Disabled)
Sent lighting command [1, 0] (InControl Disabled)
Sent lighting command [3, 1] (InControl Disabled)
Sent lighting command [2, 0] (InControl Disabled)
Sent lighting command [4, 1] (InControl Disabled)
Sent lighting command [3, 0] (InControl Disabled)
Sent lighting command [5, 1] (InControl Disabled)
Sent lighting command [4, 0] (InControl Disabled)
Sent lighting command [0, 1] (InControl Disabled)
Sent lighting command [1, 1] (InControl Disabled)
Sent lighting command [0, 0] (InControl Disabled)
Sent lighting command [2, 1] (InControl Disabled)
Sent lighting command [1, 0] (InControl Disabled)
Sent lighting command [3, 1] (InControl Disabled)
Sent lighting command [2, 0] (InControl Disabled)
Sent lighting command [4, 1] (InControl Disabled)
Sent lighting command [3, 0] (InControl Disabled)
Sent lighting command [5, 1] (InControl Disabled)
Sent lighting command [4, 0] (InControl Disabled)
Sent lighting command [6, 1] (InControl Disabled)
Sent lighting command [5, 0] (InControl Disabled)
Sent lighting command [0, 1] (InControl Disabled)
Sent lighting command [1, 1] (InControl Disabled)
Sent lighting command [0, 0] (InControl Disabled)
Sent lighting command [2, 1] (InControl Disabled)
Sent lighting command [1, 0] (InControl Disabled)
Sent lighting command [3, 1] (InControl Disabled)
Sent lighting command [2, 0] (InControl Disabled)
Sent lighting command [4, 1] (InControl Disabled)
Sent lighting command [3, 0] (InControl Disabled)
Sent lighting command [5, 1] (InControl Disabled)
Sent lighting command [4, 0] (InControl Disabled)
Sent lighting command [6, 1] (InControl Disabled)
Sent lighting command [5, 0] (InControl Disabled)
Sent lighting command [7, 1] (InControl Disabled)
Sent lighting command [6, 0] (InControl Disabled)
Sent lighting command [0, 1] (InControl Disabled)
Sent lighting command [1, 1] (InControl Disabled)
Sent lighting command [0, 0] (InControl Disabled)
Sent lighting command [2, 1] (InControl Disabled)
Sent lighting command [1, 0] (InControl Disabled)
Sent lighting command [3, 1] (InControl Disabled)
Sent lighting command [2, 0] (InControl Disabled)
Sent lighting command [4, 1] (InControl Disabled)
Sent lighting command [3, 0] (InControl Disabled)
Sent lighting command [5, 1] (InControl Disabled)
Sent lighting command [4, 0] (InControl Disabled)
Sent lighting command [6, 1] (InControl Disabled)
Sent lighting command [5, 0] (InControl Disabled)
Sent lighting command [7, 1] (InControl Disabled)
Sent lighting command [6, 0] (InControl Disabled)
Sent lighting command [7, 0] (InControl Disabled)
Sent lighting command [1, 1] (InControl Disabled)
Sent lighting command [0, 0] (InControl Disabled)
Sent lighting command [2, 1] (InControl Disabled)
Sent lighting command [1, 0] (InControl Disabled)
Sent lighting command [3, 1] (InControl Disabled)
Sent lighting command [2, 0] (InControl Disabled)
Sent lighting command [4, 1] (InControl Disabled)
Sent lighting command [3, 0] (InControl Disabled)
Sent lighting command [5, 1] (InControl Disabled)
Sent lighting command [4, 0] (InControl Disabled)
Sent lighting command [6, 1] (InControl Disabled)
Sent lighting command [5, 0] (InControl Disabled)
Sent lighting command [7, 1] (InControl Disabled)
Sent lighting command [6, 0] (InControl Disabled)
Sent lighting command [7, 0] (InControl Disabled)
Sent lighting command [2, 1] (InControl Disabled)
Sent lighting command [1, 0] (InControl Disabled)
Sent lighting command [3, 1] (InControl Disabled)
Sent lighting command [2, 0] (InControl Disabled)
Sent lighting command [4, 1] (InControl Disabled)
Sent lighting command [3, 0] (InControl Disabled)
Sent lighting command [5, 1] (InControl Disabled)
Sent lighting command [4, 0] (InControl Disabled)
Sent lighting command [6, 1] (InControl Disabled)
Sent lighting command [5, 0] (InControl Disabled)
Sent lighting command [7, 1] (InControl Disabled)
Sent lighting command [6, 0] (InControl Disabled)
Sent lighting command [7, 0] (InControl Disabled)
Sent lighting command [3, 1] (InControl Disabled)
Sent lighting command [2, 0] (InControl Disabled)
Sent lighting command [4, 1] (InControl Disabled)
Sent lighting command [3, 0] (InControl Disabled)
Sent lighting command [5, 1] (InControl Disabled)
Sent lighting command [4, 0] (InControl Disabled)
Sent lighting command [6, 1] (InControl Disabled)
Sent lighting command [5, 0] (InControl Disabled)
Sent lighting command [7, 1] (InControl Disabled)
Sent lighting command [6, 0] (InControl Disabled)
Sent lighting command [7, 0] (InControl Disabled)
Sent lighting command [4, 1] (InControl Disabled)
Sent lighting command [3, 0] (InControl Disabled)
Sent lighting command [5, 1] (InControl Disabled)
Sent lighting command [4, 0] (InControl Disabled)
Sent lighting command [6, 1] (InControl Disabled)
Sent lighting command [5, 0] (InControl Disabled)
Sent lighting command [7, 1] (InControl Disabled)
Sent lighting command [6, 0] (InControl Disabled)
Sent lighting command [7, 0] (InControl Disabled)
Sent lighting command [5, 1] (InControl Disabled)
Sent lighting command [4, 0] (InControl Disabled)
Sent lighting command [6, 1] (InControl Disabled)
Sent lighting command [5, 0] (InControl Disabled)
Sent lighting command [7, 1] (InControl Disabled)
Sent lighting command [6, 0] (InControl Disabled)
Sent lighting command [7, 0] (InControl Disabled)
Sent lighting command [6, 1] (InControl Disabled)
Sent lighting command [5, 0] (InControl Disabled)
Sent lighting command [7, 1] (InControl Disabled)
Sent lighting command [6, 0] (InControl Disabled)
Sent lighting command [7, 0] (InControl Disabled)
Sent lighting command [7, 1] (InControl Disabled)
Sent lighting command [6, 0] (InControl Disabled)
Sent lighting command [7, 0] (InControl Disabled)
Sent lighting command [7, 0] (InControl Disabled)
Sent lighting reset signal
Initialisation complete
————————————————————————————————————————————————————
————————————————————————————————————————————————————


Event:          System          InControl       127  (On)       0x 7F 0C 9F     
Sent lighting reset signal

Primary Processor               Set Extended Mode to True       
[Event was handled]
————————————————————————————————————————————————————

Active Window:  Channel Rack
[Background:   ]
————————————————————————————————————————————————————
Sent lighting command [0, 1] (InControl Enabled)
Sent lighting command [1, 1] (InControl Enabled)
Sent lighting command [1, 0] (InControl Enabled)
Sent lighting command [3, 0] (InControl Enabled)
Sent lighting command [4, 0] (InControl Enabled)
Sent lighting command [7, 1] (InControl Enabled)
Sent lighting command [5, 0] (InControl Enabled)
Event:          Pad             Bottom 1        97   (On)       0x 61 70 9F     

Primary Processor               [Did not handle]                
Channel rack Processor          [Did not handle]
Default Processor               [Did not handle]                
[Event wasn't handled]
————————————————————————————————————————————————————

Sent lighting command [0, 1] (InControl Enabled)
Event:          Pad             Bottom 1        0    (Off)      0x 00 70 8F     

Primary Processor               [Did not handle]                
Channel rack Processor          Channel Rack: Next UI mode      
[Event was handled]
————————————————————————————————————————————————————

Sent lighting command [0, 0] (InControl Enabled)
Sent lighting command [0, 1] (InControl Enabled)
Sent lighting command [1, 0] (InControl Enabled)
Sent lighting command [1, 1] (InControl Enabled)
Sent lighting command [3, 0] (InControl Enabled)
Sent lighting command [4, 0] (InControl Enabled)
Sent lighting command [5, 0] (InControl Enabled)
Sent lighting command [7, 1] (InControl Enabled)
Sent lighting command [2, 0] (InControl Enabled)
Sent lighting command [3, 0] (InControl Enabled)
Sent lighting command [7, 1] (InControl Enabled)
Sent lighting command [4, 0] (InControl Enabled)
Sent lighting command [6, 1] (InControl Enabled)
Sent lighting command [5, 0] (InControl Enabled)
Sent lighting command [5, 1] (InControl Enabled)
Sent lighting command [4, 1] (InControl Enabled)
Sent lighting command [6, 0] (InControl Enabled)
Sent lighting command [7, 0] (InControl Enabled)
Sent lighting command [7, 0] (InControl Enabled)
Sent lighting command [0, 0] (InControl Enabled)
Sent lighting command [0, 1] (InControl Enabled)
Sent lighting command [1, 0] (InControl Enabled)
Sent lighting command [2, 0] (InControl Enabled)
Sent lighting command [3, 0] (InControl Enabled)
Sent lighting command [4, 0] (InControl Enabled)
Sent lighting command [4, 1] (InControl Enabled)
Sent lighting command [5, 0] (InControl Enabled)
Sent lighting command [5, 1] (InControl Enabled)
Sent lighting command [6, 0] (InControl Enabled)
Sent lighting command [6, 1] (InControl Enabled)
Sent lighting command [7, 0] (InControl Enabled)
Sent lighting command [7, 1] (InControl Enabled)
Sent lighting command [1, 1] (InControl Enabled)
Sent lighting command [0, 1] (InControl Enabled)
Sent lighting command [1, 0] (InControl Enabled)
Sent lighting command [2, 1] (InControl Enabled)
Sent lighting command [3, 1] (InControl Enabled)
Sent lighting command [4, 1] (InControl Enabled)
Active Window:  Script output
[Background:  Channel Rack ]
————————————————————————————————————————————————————
Sent lighting command [1, 0] (InControl Enabled)
Sent lighting command [1, 1] (InControl Enabled)
Sent lighting command [2, 1] (InControl Enabled)
Sent lighting command [3, 1] (InControl Enabled)
Sent lighting command [4, 1] (InControl Enabled)
Sent lighting command [1, 1] (InControl Enabled)
Sent lighting command [1, 0] (InControl Enabled)
Sent lighting command [3, 0] (InControl Enabled)
Sent lighting command [4, 0] (InControl Enabled)
Sent lighting command [7, 1] (InControl Enabled)
Sent lighting command [5, 0] (InControl Enabled)

**Comment by MaddyGuthridge** [comment] 2020-08-31 02:21
As v2.0 has been released with a revamp of the shift menu, this issue is probably fixed. Can I get some confirmation?

**Comment by MaddyGuthridge** [comment] 2020-09-10 03:52
If I don't receive any sort of reply in the next few days, I'll close this issue.

**Comment by MaddyGuthridge** [comment] 2020-09-25 04:34
Closed due to inactivity

**Closed as completed by MaddyGuthridge** 2020-09-25 04:34 UTC
Labels: bug, couldn't reproduce
