### ISSUE TITLE
Trying to link fader 9 crashes script

### ISSUE THREAD

**Issue by andreykaipov** [MiguelGuthridge/Novation-LaunchKey-Mk2-Script#48] opened 2021-01-30 03:47 UTC
Playing around with this again. With _InControl_ mode off, I tried to link fader 9 to an FL Studio thing, but that crashed the script. No output at all, but I figured out it was the following lines:

https://github.com/MiguelGuthridge/Novation-LaunchKey-Mk2-Script/blob/v2.1.1/pluginprocessors/processplugins.py#L92-L116

Seems like since fader 9 is being handled there outside of _InControl_ mode, linking it causes an issue. I couldn't really find a way to gracefully continue or print out an indication on the UI that the fader is already linked, so I've just commented it out to get around the crash. Personally not a big deal for me since I don't see much use in being able to adjust the selected channel's volume when I could quickly go back to _InControl_ mode and do it from there.

**Comment by MaddyGuthridge** [comment] 2021-02-01 04:23
This is most-likely due to an issue with the script incorrectly parsing the flags that tell it if it's safe to do things. Currently, the workaround is to put the controller into the Unassigned note mode (check the Wiki for instructions), then link it up.

**Comment by MaddyGuthridge** [comment] 2021-02-01 04:24
Duplicate of #25

**Closed as completed by MaddyGuthridge** 2021-02-01 04:24 UTC
Labels: bug, duplicate, reproduced
